name: Deploy to ECR

on:
  push:
    branches: [ main ]


jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env: 
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-own-repo
        IMAGE_TAG: cats
      
        
      run: |
          cd cats/
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker run -d -p 8080:80 --name my-first-repo-cats $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps
          sleep 5
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
    - name: Build,test, tag and push image to Amazon ECR
      env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: my-own-repo
          IMAGE_TAG: dogs
          
      run: |
          cd dogs/
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker run -d -p 8081:80 --name my-first-repo-dogs $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps
          # Push the docker image to ECR repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG   
